# Checks the format, linting and tsc on all pull requests
name: Check
on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: lts

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Yarn Install
        run: yarn --immutable
      - name: Format Check
        run: yarn format:check
      - name: Lint Check
        run: yarn lint:check
      - name: TSC Check
        run: yarn tsc:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Yarn Install
        run: yarn --immutable
      - name: Test
        run: yarn test

